import { useState } from 'react'
import { Navigate, useLocation, useNavigate } from 'react-router-dom'
import { getApiError } from '../../services/api.js'
import { processDemoPayment } from '../../services/payments.js'


function Checkout() {

  const { state } =  useLocation(); const navigate = useNavigate(); const booking = state?.booking
  const [form, setForm] =  useState({ cardName: '', cardNumber: '', expiryDate: '', cvv: '' }); const [loading, setLoading] = useState(false); const [error, setError] = useState('')
  if (!booking) return  <Navigate to="/events" replace />
  const submit = async (event) => { event.preventDefault(); setLoading(true); setError(''); try { const result = await processDemoPayment({ bookingId: booking._id, ...form }); navigate('/user/tickets', { state: { paymentSuccess: true, tickets: result.tickets } }) } catch (requestError) { setError(getApiError(requestError, 'Payment failed.')) } finally { setLoading(false) } }
  const field = (name) => ({ value: form[name], onChange: (e) => setForm({ ...form, [name]: e.target.value }) })
  return <main className="bg-gray-50 py-12"><div className="mx-auto grid max-w-5xl gap-8 px-4 md:grid-cols-2"><section className="rounded-lg border bg-white p-6 shadow-sm"><h1 className="text-2xl font-bold text-gray-900">Checkout</h1><dl className="mt-6 space-y-4 text-sm"><div className="flex justify-between"><dt className="text-gray-500">Event</dt><dd className="font-medium">{state.event?.title}</dd></div><div className="flex justify-between"><dt className="text-gray-500">Ticket</dt><dd className="font-medium">{state.ticketType?.name}</dd></div><div className="flex justify-between"><dt className="text-gray-500">Quantity</dt><dd className="font-medium">{booking.quantity}</dd></div><div className="flex justify-between border-t pt-4 text-base"><dt className="font-semibold">Total</dt><dd className="font-bold">${booking.totalAmount}</dd></div></dl></section><form onSubmit={submit} className="rounded-lg border bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Demo Payment</h2><p className="mt-2 text-sm text-gray-600">Kani waa demo payment; lacag dhab ah lama qaadayo.</p>{error && <p className="mt-4 rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}<label className="mt-5 block text-sm font-medium">Name on Card<input required {...field('cardName')} className="mt-2 w-full rounded-lg border px-3 py-2" /></label><label className="mt-4 block text-sm font-medium">Card Number<input required inputMode="numeric" placeholder="4242424242424242" {...field('cardNumber')} className="mt-2 w-full rounded-lg border px-3 py-2" /></label><div className="mt-4 grid grid-cols-2 gap-4"><label className="text-sm font-medium">Expiry<input required placeholder="12/30" {...field('expiryDate')} className="mt-2 w-full rounded-lg border px-3 py-2" /></label><label className="text-sm font-medium">CVV<input required inputMode="numeric" {...field('cvv')} className="mt-2 w-full rounded-lg border px-3 py-2" /></label></div><button disabled={loading} className="mt-6 w-full rounded-lg bg-blue-600 px-4 py-3 font-semibold text-white hover:bg-blue-700 disabled:opacity-60">{loading ? 'Processing...' : 'Pay Now'}</button></form></div></main>
}
export default Checkout
